services:
 django:
   build: .
   container_name: django-sqlite-dev
   ports:
     - "2222:22"
     - "8000:8000"
   volumes:
     - .:/workspace
   env_file:
     - .env
   working_dir: /workspace
   tty: true
   stdin_open: true
