# Generated by Django 6.0.3 on 2026-04-21 06:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='建物名称')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': '建物',
                'verbose_name_plural': '建物',
                'db_table': 'buildings',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='設備名称')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': '設備',
                'verbose_name_plural': '設備',
                'db_table': 'facilities',
            },
        ),
        migrations.CreateModel(
            name='DepartmentRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(db_column='department_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.department', verbose_name='所属')),
            ],
            options={
                'verbose_name': '所属別会議室',
                'verbose_name_plural': '所属別会議室',
                'db_table': 'department_rooms',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='室名')),
                ('capacity', models.PositiveIntegerField(verbose_name='収容人数')),
                ('floor', models.IntegerField(blank=True, null=True, verbose_name='階数')),
                ('is_active', models.BooleanField(default=True, verbose_name='利用可能')),
                ('building', models.ForeignKey(blank=True, db_column='building_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='reservations.building', verbose_name='建物')),
                ('departments', models.ManyToManyField(blank=True, through='reservations.DepartmentRoom', to='accounts.department', verbose_name='所属別表示設定')),
            ],
            options={
                'verbose_name': '会議室',
                'verbose_name_plural': '会議室',
                'db_table': 'rooms',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_by', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('purpose', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('participants', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('is_cancelled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservations.room', verbose_name='会議室')),
            ],
            options={
                'db_table': 'reservations',
            },
        ),
        migrations.AddField(
            model_name='departmentroom',
            name='room',
            field=models.ForeignKey(db_column='room_id', on_delete=django.db.models.deletion.CASCADE, to='reservations.room', verbose_name='会議室'),
        ),
        migrations.CreateModel(
            name='RoomFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.ForeignKey(db_column='facility_id', on_delete=django.db.models.deletion.CASCADE, to='reservations.facility', verbose_name='設備')),
                ('room', models.ForeignKey(db_column='room_id', on_delete=django.db.models.deletion.CASCADE, to='reservations.room', verbose_name='会議室')),
            ],
            options={
                'verbose_name': '会議室設備',
                'verbose_name_plural': '会議室設備',
                'db_table': 'room_facilities',
                'unique_together': {('room', 'facility')},
            },
        ),
        migrations.AddField(
            model_name='room',
            name='facilities',
            field=models.ManyToManyField(blank=True, through='reservations.RoomFacility', to='reservations.facility', verbose_name='設備'),
        ),
        migrations.AlterUniqueTogether(
            name='departmentroom',
            unique_together={('department', 'room')},
        ),
    ]
