# Generated by Django 6.0.3 on 2026-04-21 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_remove_reservation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='start_time',
        ),
    ]
