# Generated by Django 6.0.3 on 2026-04-21 06:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100, unique=True, verbose_name='所属名称')),
                ('created_at', models.DateTimeField(db_column='created_at', default=django.utils.timezone.now, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': '所属',
                'verbose_name_plural': '所属',
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('login_id', models.CharField(db_column='login_id', max_length=50, unique=True, verbose_name='ログインID')),
                ('name', models.CharField(db_column='name', max_length=100, verbose_name='氏名')),
                ('password', models.CharField(db_column='password_hash', max_length=255, verbose_name='パスワードハッシュ')),
                ('role', models.CharField(choices=[('admin', 'admin'), ('user', 'user')], db_column='role', default='user', max_length=10, verbose_name='権限種別')),
                ('is_active', models.BooleanField(db_column='is_active', default=True, verbose_name='有効フラグ')),
                ('last_login', models.DateTimeField(blank=True, db_column='last_login_at', null=True, verbose_name='最終ログイン日時')),
                ('created_at', models.DateTimeField(db_column='created_at', default=django.utils.timezone.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', verbose_name='更新日時')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('department', models.ForeignKey(blank=True, db_column='department_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.department', verbose_name='所属')),
            ],
            options={
                'verbose_name': 'ユーザー',
                'verbose_name_plural': 'ユーザー',
                'db_table': 'users',
            },
        ),
    ]
