# Generated by Django 6.0.3 on 2026-04-20 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': '所属', 'verbose_name_plural': '所属'},
        ),
    ]
